FROM node:18-alpine

WORKDIR /usr/fakeqgis/mock-server

RUN npm install -g json-server@0.17.4

COPY mock ./mock

EXPOSE 3001

ENV MOCK_DATA_FILE=db.legacy.json
ENV MOCK_RESOURCE_NAME=soils

CMD ["json-server", "--watch", "mock/db.js", "--host", "0.0.0.0", "--port", "3001"]
